
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BD
{

    public Nullable<long> index { get; set; }

    public Nullable<double> Unnamed__0 { get; set; }

    public string Data { get; set; }

    public string Estado { get; set; }

    public Nullable<System.DateTime> Fecha_Actualización_ { get; set; }

    public string Responsable { get; set; }

    public string Tema { get; set; }

    public string Observación_ { get; set; }

    public string Acción { get; set; }

    public string Monitoreo { get; set; }

    public int id { get; set; }

}

}
