//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_Data()
        {
            this.D_INVESTIGACION = new HashSet<D_INVESTIGACION>();
            this.D_PRIORIZACION = new HashSet<D_PRIORIZACION>();
        }
    
        public decimal id { get; set; }
        public string data { get; set; }
        public string id_data { get; set; }
        public string estado { get; set; }
        public string desarrollo { get; set; }
        public string investigacion { get; set; }
        public string descripcion { get; set; }
        public string slogan { get; set; }
        public string vista { get; set; }
        public string repositorio_dropbox { get; set; }
        public string logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_INVESTIGACION> D_INVESTIGACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_PRIORIZACION> D_PRIORIZACION { get; set; }
    }
}
