//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_INVESTIGACION
    {
        public decimal id { get; set; }
        public Nullable<double> numero { get; set; }
        public string tema { get; set; }
        public string responsable { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_avance { get; set; }
        public Nullable<System.DateTime> fecha_termino { get; set; }
        public string comentario { get; set; }
        public string accion { get; set; }
        public string seguimiento { get; set; }
        public decimal D_Data_id_data { get; set; }
    
        public virtual D_Data D_Data { get; set; }
    }
}
