//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_PRIORIZACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_PRIORIZACION()
        {
            this.D_PRODUCTO = new HashSet<D_PRODUCTO>();
        }
    
        public decimal id { get; set; }
        public string producto_previo { get; set; }
        public string nombre { get; set; }
        public Nullable<double> secuencia { get; set; }
        public string pais { get; set; }
        public string integrado { get; set; }
        public string id_producto { get; set; }
        public Nullable<double> prioridad { get; set; }
        public string estado { get; set; }
        public Nullable<double> avance { get; set; }
        public string responsable_desarrollo { get; set; }
        public string responsable_informacion { get; set; }
        public string tecnologia { get; set; }
        public string tarea { get; set; }
        public string db { get; set; }
        public string plataforma { get; set; }
        public string control_calidad { get; set; }
        public string odoo { get; set; }
        public string shopify { get; set; }
        public Nullable<System.DateTime> fecha_estimada { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public decimal D_Data_id_data { get; set; }
    
        public virtual D_Data D_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_PRODUCTO> D_PRODUCTO { get; set; }
    }
}
