//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_PRODUCTO()
        {
            this.D_SHOPIFY = new HashSet<D_SHOPIFY>();
        }
    
        public decimal id { get; set; }
        public Nullable<long> corr_Producto { get; set; }
        public string data { get; set; }
        public string pais { get; set; }
        public string id_producto { get; set; }
        public string producto_asociado { get; set; }
        public string nombre_comercial { get; set; }
        public string estado { get; set; }
        public Nullable<double> avance { get; set; }
        public string responsable_desarrollo { get; set; }
        public string responsable_informacion { get; set; }
        public string tecnologia { get; set; }
        public string host { get; set; }
        public string link_odoo { get; set; }
        public Nullable<System.DateTime> fecha_publicación { get; set; }
        public string escala { get; set; }
        public string periodo { get; set; }
        public string actualizaciones { get; set; }
        public string tipo_producto { get; set; }
        public string fuentes { get; set; }
        public string ref_principal { get; set; }
        public string competencia { get; set; }
        public string vista { get; set; }
        public string repositorio_dropbox { get; set; }
        public string logo { get; set; }
        public Nullable<double> observaciones { get; set; }
        public string miniatura { get; set; }
        public string portada_shopify { get; set; }
        public string parrafo_enganche { get; set; }
        public string variante_1 { get; set; }
        public Nullable<double> precio1_usd { get; set; }
        public string variante_2 { get; set; }
        public Nullable<double> precio2_usd { get; set; }
        public string variante_3 { get; set; }
        public Nullable<double> precio3_usd { get; set; }
        public string variable_filtro1 { get; set; }
        public string variable_filtro2 { get; set; }
        public string variable_filtro3 { get; set; }
        public string descripcion { get; set; }
        public string CAR_tipo_prod { get; set; }
        public string CAR_var1_disponible { get; set; }
        public string CAR_var2_disponible { get; set; }
        public string CAR_var3_disponible { get; set; }
        public string CAR_periodo { get; set; }
        public string CAR_proveedor { get; set; }
        public string CAR_colección { get; set; }
        public string ESP_tecnología { get; set; }
        public string ESP_incluye { get; set; }
        public string ESP_uso_disp { get; set; }
        public string ESP_fuentes_ { get; set; }
        public string ACC_recibirás { get; set; }
        public string ACC_licencia_uso { get; set; }
        public string ACC_actualizaciones { get; set; }
        public Nullable<double> ACC_numero_usuarios { get; set; }
        public string etiquetas { get; set; }
        public decimal D_PRIORIZACION_id_priorizacion { get; set; }
    
        public virtual D_PRIORIZACION D_PRIORIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_SHOPIFY> D_SHOPIFY { get; set; }
    }
}
