
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Data
{

    public Nullable<long> index { get; set; }

    public Nullable<double> Unnamed__0 { get; set; }

    public string Data1 { get; set; }

    public Nullable<long> id_data { get; set; }

    public string Estado { get; set; }

    public string Desarrollo { get; set; }

    public string Investigación { get; set; }

    public string Breve_Descripción { get; set; }

    public string Slogan___Cita { get; set; }

    public string Vistas { get; set; }

    public string Repositorio_Dropbox { get; set; }

    public string Link_Logo { get; set; }

    public int id { get; set; }

}

}
