
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Detalle_Productos
{

    public Nullable<long> index { get; set; }

    public Nullable<double> Unnamed__0 { get; set; }

    public string Data { get; set; }

    public string id_producto { get; set; }

    public string Plazo_Producto { get; set; }

    public string Producto { get; set; }

    public string Secciones { get; set; }

    public string Sub_secciones { get; set; }

    public string Variables { get; set; }

    public string Fuente { get; set; }

    public string Situación_Variable { get; set; }

    public Nullable<System.DateTime> Fecha_Actualización { get; set; }

    public Nullable<double> Observaciones { get; set; }

    public int id { get; set; }

}

}
