//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigacio
    {
        public Nullable<long> index { get; set; }
        public Nullable<long> N_ { get; set; }
        public string Tema_Investigación_ { get; set; }
        public string Responsables_ { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Termino { get; set; }
        public string Chile { get; set; }
        public string Panamá_ { get; set; }
        public string Guatemala { get; set; }
        public string Honduras { get; set; }
        public string El_Salvador { get; set; }
        public string Link_1 { get; set; }
        public string Link_2 { get; set; }
        public int id { get; set; }
    }
}
