//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class listaProductosEntities : DbContext
    {
        public listaProductosEntities()
            : base("name=listaProductosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BD> BDs { get; set; }
        public virtual DbSet<Data> Datas { get; set; }
        public virtual DbSet<Detalle_Productos> Detalle_Productos { get; set; }
        public virtual DbSet<Investigacio> Investigacios { get; set; }
        public virtual DbSet<Monitoreo_Invest> Monitoreo_Invest { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Prioridad> Prioridads { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Shopify> Shopifies { get; set; }
        public virtual DbSet<ShopifyOriginal> ShopifyOriginals { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
    }
}
