
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Monitoreo_Invest
{

    public Nullable<long> index { get; set; }

    public Nullable<double> N_ { get; set; }

    public string Tema_institución_Investigación_ { get; set; }

    public string Responsable { get; set; }

    public Nullable<System.DateTime> Fecha_inicio { get; set; }

    public Nullable<System.DateTime> Fecha_avance { get; set; }

    public Nullable<System.DateTime> Fecha_Termino { get; set; }

    public string Comentario { get; set; }

    public string Acción { get; set; }

    public string Seguimiento { get; set; }

    public int id { get; set; }

}

}
