
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Pais
{

    public Nullable<long> index { get; set; }

    public Nullable<double> Unnamed__0 { get; set; }

    public string País { get; set; }

    public Nullable<long> id_país { get; set; }

    public int id { get; set; }

}

}
