
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Prioridad
{

    public Nullable<long> index { get; set; }

    public Nullable<double> Unnamed__0 { get; set; }

    public string Data { get; set; }

    public string Producto_Previos { get; set; }

    public Nullable<double> Secuencia { get; set; }

    public string País { get; set; }

    public string Integrado_PRODUCTOS { get; set; }

    public string id_producto { get; set; }

    public Nullable<double> Prioridad1 { get; set; }

    public string Estado { get; set; }

    public Nullable<double> Avance { get; set; }

    public string Responsable_Desarrollo { get; set; }

    public string Responsable_Información { get; set; }

    public string Tecnología { get; set; }

    public string Tareas_Elementos { get; set; }

    public Nullable<double> Columna1 { get; set; }

    public string Tecnología2 { get; set; }

    public Nullable<double> Fecha_estimada { get; set; }

    public int id { get; set; }

    public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }

}

}
