
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Shopify
{

    public Nullable<long> index { get; set; }

    public Nullable<long> id_data { get; set; }

    public Nullable<long> Corr_Producto { get; set; }

    public string Data { get; set; }

    public string id_producto { get; set; }

    public string Producto_asociado_ { get; set; }

    public string Nombre_comercial { get; set; }

    public Nullable<double> Variante { get; set; }

    public Nullable<double> Corr_variante { get; set; }

    public Nullable<double> id_prod_var { get; set; }

    public string Estado { get; set; }

    public Nullable<double> Avance { get; set; }

    public string Responsable_Desarrollo { get; set; }

    public string Responsable_Información { get; set; }

    public string PORTADA_SHOPIFY { get; set; }

    public string Párrafo_enganche { get; set; }

    public string Variante_1 { get; set; }

    public Nullable<double> Precio_1 { get; set; }

    public string Variante_2 { get; set; }

    public Nullable<double> Precio_2 { get; set; }

    public string Variante_3 { get; set; }

    public Nullable<double> Precio_3 { get; set; }

    public Nullable<double> Variable_filtro1 { get; set; }

    public Nullable<double> Variable_filtro2 { get; set; }

    public Nullable<double> Variable_filtro3 { get; set; }

    public string Descripción__Indicar_qué_permite_ver_o_hacer_el_producto__ { get; set; }

    public string CAR_Tipo_Prod { get; set; }

    public string CAR_Var1_Disponible { get; set; }

    public string CAR_Periodo { get; set; }

    public string CAR_Proveedor { get; set; }

    public string CAR_Colección { get; set; }

    public string ESP_Tecnología { get; set; }

    public string Host_ { get; set; }

    public string Link_Odoo { get; set; }

    public Nullable<double> Fecha_Publicación { get; set; }

    public string País { get; set; }

    public string Escala_ { get; set; }

    public string ESP_Periodo { get; set; }

    public string ESP_Incluye { get; set; }

    public string ESP_Uso_Disp_ { get; set; }

    public string ESP_Fuentes_ { get; set; }

    public string ACC_Recibirás { get; set; }

    public string ACC_Licencia_uso { get; set; }

    public string ACC_Actualizaciones { get; set; }

    public Nullable<double> ACC_N__usuarios { get; set; }

    public string Etiquetas { get; set; }

    public string Vistas { get; set; }

    public string Repositorio_Dropbox { get; set; }

    public string Link_Logo { get; set; }

    public Nullable<double> Observaciones { get; set; }

    public string Miniatura { get; set; }

    public int id { get; set; }

}

}
