//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public Nullable<long> index { get; set; }
        public Nullable<double> Unnamed__0 { get; set; }
        public string Data { get; set; }
        public Nullable<double> Producto { get; set; }
        public string Sección { get; set; }
        public string Tema { get; set; }
        public Nullable<long> Verificador { get; set; }
        public string Variables { get; set; }
        public string ID_VAR { get; set; }
        public int id { get; set; }
    }
}
